version: '3.9'

services:
  postgres:
    image: postgres:16beta2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

  deno:
    container_name: deno
    image: deno
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    links:
      - postgres
volumes:
  db:
    driver: local
