version: '3.9'

services:
  postgres:
    image: postgres:16beta2-alpine
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=test
    #    ports:
    #      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

  deno:
    container_name: deno
    image: deno
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    environment:
      - DBUSER=pguser
      - DBPASSWORD=pgpass
      - DBNAME=test
      - PORT=8080
    links:
      - postgres
volumes:
  db:
    driver: local
